name: eng-task-grading

services:

  eng-task-grading-fe:
    container_name: eng-task-grading-fe
    build:
      context: ../eng-task-grading-react-fe
    environment:
      BACKEND_URL: ${BACKEND_URL}
      CLOUDFLARE_ENABLED: ${CLOUDFLARE_ENABLED:-false}
    ports:
      - "${FE_HTTP_PORT:-8100}:80"
      - "${FE_HTTPS_PORT:-8101}:443"
    networks:
      - eng-task-grading-net

  eng-task-grading-be:
    # image: ${DOCKER_REGISTRY-}engtaskgradingnetbe
    container_name: eng-task-grading-be
    build:
      context: ../EngTaskGradingNetBESolution
      dockerfile: ../EngTaskGradingNetBESolution/EngTaskgradingNetBE/Dockerfile
      # image: eng-task-grading-be:latest
    environment:
      DOTNET_ENVIRONMENT: Release
      ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 443
      AppSettings__Security__AccessTokenJwtSecretKey: ${JWT_SECRET_KEY}
      AppSettings__Emails__Configs__Osu__SenderEmail: ${OSU_SENDER_EMAIL}
      AppSettings__Emails__Configs__Osu__SenderPassword: ${OSU_SENDER_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${BE_HTTP_PORT:-8103}:8080"
      - "${BE_HTTPS_PORT:-8104}:443"
    networks:
      - eng-task-grading-net

  eng-task-grading-db:
    container_name: eng-task-grading-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-8105}:1433"
    networks:
      - eng-task-grading-net
    volumes:
      - eng-task-grading-db-data:/var/opt/mssql

networks:
  eng-task-grading-net:
    driver: bridge

volumes:
  eng-task-grading-db-data:

