/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as StudentViewLoginRouteImport } from './routes/studentView/login'
import { Route as StudentViewHomeRouteImport } from './routes/studentView/home'
import { Route as CoursesIdRouteImport } from './routes/courses/$id'
import { Route as AttendancesIdRouteImport } from './routes/attendances/$id'
import { Route as AttendanceDaysIdRouteImport } from './routes/attendanceDays/$id'
import { Route as StudentViewCoursesIndexRouteImport } from './routes/studentView/courses/index'
import { Route as StudentViewVerifyTokenRouteImport } from './routes/studentView/verify/$token'
import { Route as StudentViewLoginTokenRouteImport } from './routes/studentView/login/$token'
import { Route as StudentViewCoursesIdRouteImport } from './routes/studentView/courses/$id'
import { Route as CoursesIdTasksRouteImport } from './routes/courses/$id/tasks'
import { Route as CoursesIdStudentsRouteImport } from './routes/courses/$id/students'
import { Route as CoursesIdGradesRouteImport } from './routes/courses/$id/grades'
import { Route as CoursesIdAttendancesRouteImport } from './routes/courses/$id/attendances'
import { Route as AttendanceSelfSignSelfSignIdRouteImport } from './routes/attendanceSelfSign/self-sign.$id'
import { Route as AttendanceSelfSignViewInfoIdKeyRouteImport } from './routes/attendanceSelfSign/view-info.$id.$key'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentViewLoginRoute = StudentViewLoginRouteImport.update({
  id: '/studentView/login',
  path: '/studentView/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentViewHomeRoute = StudentViewHomeRouteImport.update({
  id: '/studentView/home',
  path: '/studentView/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendancesIdRoute = AttendancesIdRouteImport.update({
  id: '/attendances/$id',
  path: '/attendances/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceDaysIdRoute = AttendanceDaysIdRouteImport.update({
  id: '/attendanceDays/$id',
  path: '/attendanceDays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentViewCoursesIndexRoute = StudentViewCoursesIndexRouteImport.update({
  id: '/studentView/courses/',
  path: '/studentView/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentViewVerifyTokenRoute = StudentViewVerifyTokenRouteImport.update({
  id: '/studentView/verify/$token',
  path: '/studentView/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentViewLoginTokenRoute = StudentViewLoginTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => StudentViewLoginRoute,
} as any)
const StudentViewCoursesIdRoute = StudentViewCoursesIdRouteImport.update({
  id: '/studentView/courses/$id',
  path: '/studentView/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdTasksRoute = CoursesIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CoursesIdRoute,
} as any)
const CoursesIdStudentsRoute = CoursesIdStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CoursesIdRoute,
} as any)
const CoursesIdGradesRoute = CoursesIdGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => CoursesIdRoute,
} as any)
const CoursesIdAttendancesRoute = CoursesIdAttendancesRouteImport.update({
  id: '/attendances',
  path: '/attendances',
  getParentRoute: () => CoursesIdRoute,
} as any)
const AttendanceSelfSignSelfSignIdRoute =
  AttendanceSelfSignSelfSignIdRouteImport.update({
    id: '/attendanceSelfSign/self-sign/$id',
    path: '/attendanceSelfSign/self-sign/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttendanceSelfSignViewInfoIdKeyRoute =
  AttendanceSelfSignViewInfoIdKeyRouteImport.update({
    id: '/attendanceSelfSign/view-info/$id/$key',
    path: '/attendanceSelfSign/view-info/$id/$key',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/register': typeof RegisterRoute
  '/attendanceDays/$id': typeof AttendanceDaysIdRoute
  '/attendances/$id': typeof AttendancesIdRoute
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/studentView/home': typeof StudentViewHomeRoute
  '/studentView/login': typeof StudentViewLoginRouteWithChildren
  '/tasks/$id': typeof TasksIdRoute
  '/courses': typeof CoursesIndexRoute
  '/attendanceSelfSign/self-sign/$id': typeof AttendanceSelfSignSelfSignIdRoute
  '/courses/$id/attendances': typeof CoursesIdAttendancesRoute
  '/courses/$id/grades': typeof CoursesIdGradesRoute
  '/courses/$id/students': typeof CoursesIdStudentsRoute
  '/courses/$id/tasks': typeof CoursesIdTasksRoute
  '/studentView/courses/$id': typeof StudentViewCoursesIdRoute
  '/studentView/login/$token': typeof StudentViewLoginTokenRoute
  '/studentView/verify/$token': typeof StudentViewVerifyTokenRoute
  '/studentView/courses': typeof StudentViewCoursesIndexRoute
  '/attendanceSelfSign/view-info/$id/$key': typeof AttendanceSelfSignViewInfoIdKeyRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/register': typeof RegisterRoute
  '/attendanceDays/$id': typeof AttendanceDaysIdRoute
  '/attendances/$id': typeof AttendancesIdRoute
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/studentView/home': typeof StudentViewHomeRoute
  '/studentView/login': typeof StudentViewLoginRouteWithChildren
  '/tasks/$id': typeof TasksIdRoute
  '/courses': typeof CoursesIndexRoute
  '/attendanceSelfSign/self-sign/$id': typeof AttendanceSelfSignSelfSignIdRoute
  '/courses/$id/attendances': typeof CoursesIdAttendancesRoute
  '/courses/$id/grades': typeof CoursesIdGradesRoute
  '/courses/$id/students': typeof CoursesIdStudentsRoute
  '/courses/$id/tasks': typeof CoursesIdTasksRoute
  '/studentView/courses/$id': typeof StudentViewCoursesIdRoute
  '/studentView/login/$token': typeof StudentViewLoginTokenRoute
  '/studentView/verify/$token': typeof StudentViewVerifyTokenRoute
  '/studentView/courses': typeof StudentViewCoursesIndexRoute
  '/attendanceSelfSign/view-info/$id/$key': typeof AttendanceSelfSignViewInfoIdKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/register': typeof RegisterRoute
  '/attendanceDays/$id': typeof AttendanceDaysIdRoute
  '/attendances/$id': typeof AttendancesIdRoute
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/studentView/home': typeof StudentViewHomeRoute
  '/studentView/login': typeof StudentViewLoginRouteWithChildren
  '/tasks/$id': typeof TasksIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/attendanceSelfSign/self-sign/$id': typeof AttendanceSelfSignSelfSignIdRoute
  '/courses/$id/attendances': typeof CoursesIdAttendancesRoute
  '/courses/$id/grades': typeof CoursesIdGradesRoute
  '/courses/$id/students': typeof CoursesIdStudentsRoute
  '/courses/$id/tasks': typeof CoursesIdTasksRoute
  '/studentView/courses/$id': typeof StudentViewCoursesIdRoute
  '/studentView/login/$token': typeof StudentViewLoginTokenRoute
  '/studentView/verify/$token': typeof StudentViewVerifyTokenRoute
  '/studentView/courses/': typeof StudentViewCoursesIndexRoute
  '/attendanceSelfSign/view-info/$id/$key': typeof AttendanceSelfSignViewInfoIdKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/login'
    | '/logs'
    | '/register'
    | '/attendanceDays/$id'
    | '/attendances/$id'
    | '/courses/$id'
    | '/studentView/home'
    | '/studentView/login'
    | '/tasks/$id'
    | '/courses'
    | '/attendanceSelfSign/self-sign/$id'
    | '/courses/$id/attendances'
    | '/courses/$id/grades'
    | '/courses/$id/students'
    | '/courses/$id/tasks'
    | '/studentView/courses/$id'
    | '/studentView/login/$token'
    | '/studentView/verify/$token'
    | '/studentView/courses'
    | '/attendanceSelfSign/view-info/$id/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/login'
    | '/logs'
    | '/register'
    | '/attendanceDays/$id'
    | '/attendances/$id'
    | '/courses/$id'
    | '/studentView/home'
    | '/studentView/login'
    | '/tasks/$id'
    | '/courses'
    | '/attendanceSelfSign/self-sign/$id'
    | '/courses/$id/attendances'
    | '/courses/$id/grades'
    | '/courses/$id/students'
    | '/courses/$id/tasks'
    | '/studentView/courses/$id'
    | '/studentView/login/$token'
    | '/studentView/verify/$token'
    | '/studentView/courses'
    | '/attendanceSelfSign/view-info/$id/$key'
  id:
    | '__root__'
    | '/home'
    | '/login'
    | '/logs'
    | '/register'
    | '/attendanceDays/$id'
    | '/attendances/$id'
    | '/courses/$id'
    | '/studentView/home'
    | '/studentView/login'
    | '/tasks/$id'
    | '/courses/'
    | '/attendanceSelfSign/self-sign/$id'
    | '/courses/$id/attendances'
    | '/courses/$id/grades'
    | '/courses/$id/students'
    | '/courses/$id/tasks'
    | '/studentView/courses/$id'
    | '/studentView/login/$token'
    | '/studentView/verify/$token'
    | '/studentView/courses/'
    | '/attendanceSelfSign/view-info/$id/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  RegisterRoute: typeof RegisterRoute
  AttendanceDaysIdRoute: typeof AttendanceDaysIdRoute
  AttendancesIdRoute: typeof AttendancesIdRoute
  CoursesIdRoute: typeof CoursesIdRouteWithChildren
  StudentViewHomeRoute: typeof StudentViewHomeRoute
  StudentViewLoginRoute: typeof StudentViewLoginRouteWithChildren
  TasksIdRoute: typeof TasksIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  AttendanceSelfSignSelfSignIdRoute: typeof AttendanceSelfSignSelfSignIdRoute
  StudentViewCoursesIdRoute: typeof StudentViewCoursesIdRoute
  StudentViewVerifyTokenRoute: typeof StudentViewVerifyTokenRoute
  StudentViewCoursesIndexRoute: typeof StudentViewCoursesIndexRoute
  AttendanceSelfSignViewInfoIdKeyRoute: typeof AttendanceSelfSignViewInfoIdKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentView/login': {
      id: '/studentView/login'
      path: '/studentView/login'
      fullPath: '/studentView/login'
      preLoaderRoute: typeof StudentViewLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentView/home': {
      id: '/studentView/home'
      path: '/studentView/home'
      fullPath: '/studentView/home'
      preLoaderRoute: typeof StudentViewHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendances/$id': {
      id: '/attendances/$id'
      path: '/attendances/$id'
      fullPath: '/attendances/$id'
      preLoaderRoute: typeof AttendancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendanceDays/$id': {
      id: '/attendanceDays/$id'
      path: '/attendanceDays/$id'
      fullPath: '/attendanceDays/$id'
      preLoaderRoute: typeof AttendanceDaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentView/courses/': {
      id: '/studentView/courses/'
      path: '/studentView/courses'
      fullPath: '/studentView/courses'
      preLoaderRoute: typeof StudentViewCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentView/verify/$token': {
      id: '/studentView/verify/$token'
      path: '/studentView/verify/$token'
      fullPath: '/studentView/verify/$token'
      preLoaderRoute: typeof StudentViewVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentView/login/$token': {
      id: '/studentView/login/$token'
      path: '/$token'
      fullPath: '/studentView/login/$token'
      preLoaderRoute: typeof StudentViewLoginTokenRouteImport
      parentRoute: typeof StudentViewLoginRoute
    }
    '/studentView/courses/$id': {
      id: '/studentView/courses/$id'
      path: '/studentView/courses/$id'
      fullPath: '/studentView/courses/$id'
      preLoaderRoute: typeof StudentViewCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/tasks': {
      id: '/courses/$id/tasks'
      path: '/tasks'
      fullPath: '/courses/$id/tasks'
      preLoaderRoute: typeof CoursesIdTasksRouteImport
      parentRoute: typeof CoursesIdRoute
    }
    '/courses/$id/students': {
      id: '/courses/$id/students'
      path: '/students'
      fullPath: '/courses/$id/students'
      preLoaderRoute: typeof CoursesIdStudentsRouteImport
      parentRoute: typeof CoursesIdRoute
    }
    '/courses/$id/grades': {
      id: '/courses/$id/grades'
      path: '/grades'
      fullPath: '/courses/$id/grades'
      preLoaderRoute: typeof CoursesIdGradesRouteImport
      parentRoute: typeof CoursesIdRoute
    }
    '/courses/$id/attendances': {
      id: '/courses/$id/attendances'
      path: '/attendances'
      fullPath: '/courses/$id/attendances'
      preLoaderRoute: typeof CoursesIdAttendancesRouteImport
      parentRoute: typeof CoursesIdRoute
    }
    '/attendanceSelfSign/self-sign/$id': {
      id: '/attendanceSelfSign/self-sign/$id'
      path: '/attendanceSelfSign/self-sign/$id'
      fullPath: '/attendanceSelfSign/self-sign/$id'
      preLoaderRoute: typeof AttendanceSelfSignSelfSignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendanceSelfSign/view-info/$id/$key': {
      id: '/attendanceSelfSign/view-info/$id/$key'
      path: '/attendanceSelfSign/view-info/$id/$key'
      fullPath: '/attendanceSelfSign/view-info/$id/$key'
      preLoaderRoute: typeof AttendanceSelfSignViewInfoIdKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesIdRouteChildren {
  CoursesIdAttendancesRoute: typeof CoursesIdAttendancesRoute
  CoursesIdGradesRoute: typeof CoursesIdGradesRoute
  CoursesIdStudentsRoute: typeof CoursesIdStudentsRoute
  CoursesIdTasksRoute: typeof CoursesIdTasksRoute
}

const CoursesIdRouteChildren: CoursesIdRouteChildren = {
  CoursesIdAttendancesRoute: CoursesIdAttendancesRoute,
  CoursesIdGradesRoute: CoursesIdGradesRoute,
  CoursesIdStudentsRoute: CoursesIdStudentsRoute,
  CoursesIdTasksRoute: CoursesIdTasksRoute,
}

const CoursesIdRouteWithChildren = CoursesIdRoute._addFileChildren(
  CoursesIdRouteChildren,
)

interface StudentViewLoginRouteChildren {
  StudentViewLoginTokenRoute: typeof StudentViewLoginTokenRoute
}

const StudentViewLoginRouteChildren: StudentViewLoginRouteChildren = {
  StudentViewLoginTokenRoute: StudentViewLoginTokenRoute,
}

const StudentViewLoginRouteWithChildren =
  StudentViewLoginRoute._addFileChildren(StudentViewLoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  RegisterRoute: RegisterRoute,
  AttendanceDaysIdRoute: AttendanceDaysIdRoute,
  AttendancesIdRoute: AttendancesIdRoute,
  CoursesIdRoute: CoursesIdRouteWithChildren,
  StudentViewHomeRoute: StudentViewHomeRoute,
  StudentViewLoginRoute: StudentViewLoginRouteWithChildren,
  TasksIdRoute: TasksIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  AttendanceSelfSignSelfSignIdRoute: AttendanceSelfSignSelfSignIdRoute,
  StudentViewCoursesIdRoute: StudentViewCoursesIdRoute,
  StudentViewVerifyTokenRoute: StudentViewVerifyTokenRoute,
  StudentViewCoursesIndexRoute: StudentViewCoursesIndexRoute,
  AttendanceSelfSignViewInfoIdKeyRoute: AttendanceSelfSignViewInfoIdKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
